#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This script generates Makefile that can be used to import countries

import argparse
import os
from hierarchy import Hierarchy


def spath(name):
    return name.replace("/", "-")


parser = argparse.ArgumentParser(description="Prepare GeocoderNLP import")

parser.add_argument(
    "--output", default="./", help="Folder for storing generated Makefile"
)
args = parser.parse_args()

output_folder = args.output

fmake = open(os.path.join(output_folder, "Makefile.import"), "w")
fmake.write("# This Makefile is generated by script prepare_import.py\n\n")
fmake.write("BUILDER_GEOCODER=./build_geocoder.sh\n")
fmake.write("BASE_DIR=distribution\n")
fmake.write("\nall: $(BASE_DIR)/all_countries_done\n\techo All Done\n\n")

all_countries = ""

########### Main loop #############

fmake.write(
    "$(BASE_DIR)/geocoder-nlp/.directory:\n"
    + "\tmkdir -p $(BASE_DIR)/geocoder-nlp/\n\ttouch $(BASE_DIR)/geocoder-nlp/.directory\n\n"
)
fmake.write(
    "$(BASE_DIR)/geocoder-nlp/errors/.directory:\n"
    + "\tmkdir -p $(BASE_DIR)/geocoder-nlp/errors\n"
    + "\ttouch $(BASE_DIR)/geocoder-nlp/errors/.directory\n\n"
)

for root, folders, files in os.walk(Hierarchy.base_dir):
    if "name" in files and not Hierarchy.ignore(root):
        name = Hierarchy.get_full_name(root)
        cid = Hierarchy.get_id(root)
        polyjson = root + "/poly.json"

        country_target = "$(BASE_DIR)/geocoder-nlp/" + spath(cid) + ".timestamp"

        all_countries += country_target + " "
        fmake.write(
            country_target
            + ": $(BASE_DIR)/geocoder-nlp/.directory $(BASE_DIR)/geocoder-nlp/errors/.directory"
            + "\n\t$(BUILDER_GEOCODER) "
            + polyjson
            + " $(BASE_DIR) "
            + spath(cid)
            + " "
            + Hierarchy.get_postal(root)
            + ' "'
            + Hierarchy.get_postcodes(root)
            + '"\n\n'
        )

fmake.write(
    "\n$(BASE_DIR)/all_countries_done: "
    + all_countries
    + "\n\techo > $(BASE_DIR)/all_countries_done\n\n"
)

print("\nGeocoderNLP import Makefile.import ready\n")
