// Parts of this file are generated by generate_language_gui.py

import QtQuick 2.0
import QtQuick.Controls 2.2
import QtQuick.Layouts 1.3
import "."

ScrollView {

    id: main

    property bool dialogue: true

    property string title
    property string comment
    property string note
    property string value

    property var callback

    width: parent ? parent.width : 100
    height: parent ? parent.height : 100

    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff
    ScrollBar.vertical.policy: ScrollBar.AsNeeded

    ColumnLayout {
        id: column

        width: main.width
        spacing: Theme.paddingSmall

        Column {
            spacing: Theme.paddingLarge
            width: main.width

            Label {
                text: main.comment
                x: Theme.horizontalPageMargin
                width: main.width-2*x
                wrapMode: Text.WordWrap
            }

            Label {
                text: main.note
                x: Theme.horizontalPageMargin
                width: main.width-2*x
                wrapMode: Text.WordWrap
            }
        }

        // Language switches

        Switch {
            id: input_af
            width: parent.width
            text: "Afrikaans (af, Afrikaans)"
        }

        Switch {
            id: input_ar
            width: parent.width
            text: "العربية (ar, Arabic)"
        }

        Switch {
            id: input_az
            width: parent.width
            text: "azərbaycan dili (az, Azerbaijani)"
        }

        Switch {
            id: input_be
            width: parent.width
            text: "беларуская (be, Belarusian)"
        }

        Switch {
            id: input_bg
            width: parent.width
            text: "български (bg, Bulgarian)"
        }

        Switch {
            id: input_br
            width: parent.width
            text: "brezhoneg (br, Breton)"
        }

        Switch {
            id: input_bs
            width: parent.width
            text: "bosanski (bs, Bosnian)"
        }

        Switch {
            id: input_ca
            width: parent.width
            text: "català (ca, Catalan)"
        }

        Switch {
            id: input_cs
            width: parent.width
            text: "čeština (cs, Czech)"
        }

        Switch {
            id: input_cy
            width: parent.width
            text: "Cymraeg (cy, Welsh)"
        }

        Switch {
            id: input_da
            width: parent.width
            text: "dansk (da, Danish)"
        }

        Switch {
            id: input_de
            width: parent.width
            text: "Deutsch (de, German)"
        }

        Switch {
            id: input_el
            width: parent.width
            text: "Ελληνικά (el, Greek)"
        }

        Switch {
            id: input_en
            width: parent.width
            text: "English (en, English)"
        }

        Switch {
            id: input_es
            width: parent.width
            text: "español (es, Spanish)"
        }

        Switch {
            id: input_et
            width: parent.width
            text: "eesti (et, Estonian)"
        }

        Switch {
            id: input_eu
            width: parent.width
            text: "euskara (eu, Basque)"
        }

        Switch {
            id: input_fa
            width: parent.width
            text: "فارسی (fa, Persian)"
        }

        Switch {
            id: input_fi
            width: parent.width
            text: "suomi (fi, Finnish)"
        }

        Switch {
            id: input_fil
            width: parent.width
            text: "Filipino (fil, Filipino)"
        }

        Switch {
            id: input_fr
            width: parent.width
            text: "français (fr, French)"
        }

        Switch {
            id: input_ga
            width: parent.width
            text: "Gaeilge (ga, Irish)"
        }

        Switch {
            id: input_gd
            width: parent.width
            text: "Gàidhlig (gd, Scottish Gaelic)"
        }

        Switch {
            id: input_gl
            width: parent.width
            text: "galego (gl, Galician)"
        }

        Switch {
            id: input_gsw
            width: parent.width
            text: "Schwiizertüütsch (gsw, Swiss German)"
        }

        Switch {
            id: input_he
            width: parent.width
            text: "עברית (he, Hebrew)"
        }

        Switch {
            id: input_hi
            width: parent.width
            text: "हिन्दी (hi, Hindi)"
        }

        Switch {
            id: input_hr
            width: parent.width
            text: "hrvatski (hr, Croatian)"
        }

        Switch {
            id: input_hu
            width: parent.width
            text: "magyar (hu, Hungarian)"
        }

        Switch {
            id: input_id
            width: parent.width
            text: "Indonesia (id, Indonesian)"
        }

        Switch {
            id: input_is
            width: parent.width
            text: "íslenska (is, Icelandic)"
        }

        Switch {
            id: input_it
            width: parent.width
            text: "italiano (it, Italian)"
        }

        Switch {
            id: input_ja
            width: parent.width
            text: "日本語 (ja, Japanese)"
        }

        Switch {
            id: input_ka
            width: parent.width
            text: "ქართული (ka, Georgian)"
        }

        Switch {
            id: input_ko
            width: parent.width
            text: "한국어 (ko, Korean)"
        }

        Switch {
            id: input_lb
            width: parent.width
            text: "Lëtzebuergesch (lb, Luxembourgish)"
        }

        Switch {
            id: input_lt
            width: parent.width
            text: "lietuvių (lt, Lithuanian)"
        }

        Switch {
            id: input_lv
            width: parent.width
            text: "latviešu (lv, Latvian)"
        }

        Switch {
            id: input_ms
            width: parent.width
            text: "Bahasa Melayu (ms, Malay)"
        }

        Switch {
            id: input_mt
            width: parent.width
            text: "Malti (mt, Maltese)"
        }

        Switch {
            id: input_nb
            width: parent.width
            text: "norsk bokmål (nb, Norwegian Bokmål)"
        }

        Switch {
            id: input_nl
            width: parent.width
            text: "Nederlands (nl, Dutch)"
        }

        Switch {
            id: input_oc
            width: parent.width
            text: "occitan (oc, Occitan)"
        }

        Switch {
            id: input_pl
            width: parent.width
            text: "polski (pl, Polish)"
        }

        Switch {
            id: input_pt
            width: parent.width
            text: "português (pt, Portuguese)"
        }

        Switch {
            id: input_ro
            width: parent.width
            text: "română (ro, Romanian)"
        }

        Switch {
            id: input_ru
            width: parent.width
            text: "русский (ru, Russian)"
        }

        Switch {
            id: input_si
            width: parent.width
            text: "සිංහල (si, Sinhala)"
        }

        Switch {
            id: input_sk
            width: parent.width
            text: "slovenčina (sk, Slovak)"
        }

        Switch {
            id: input_sl
            width: parent.width
            text: "slovenščina (sl, Slovenian)"
        }

        Switch {
            id: input_sr
            width: parent.width
            text: "српски (sr, Serbian)"
        }

        Switch {
            id: input_sv
            width: parent.width
            text: "svenska (sv, Swedish)"
        }

        Switch {
            id: input_th
            width: parent.width
            text: "ไทย (th, Thai)"
        }

        Switch {
            id: input_tr
            width: parent.width
            text: "Türkçe (tr, Turkish)"
        }

        Switch {
            id: input_uk
            width: parent.width
            text: "українська (uk, Ukrainian)"
        }

        Switch {
            id: input_ur
            width: parent.width
            text: "اردو (ur, Urdu)"
        }

        Switch {
            id: input_vi
            width: parent.width
            text: "Tiếng Việt (vi, Vietnamese)"
        }

        Switch {
            id: input_zh
            width: parent.width
            text: "中文 (zh, Chinese)"
        }

    }

    function add(a)
    {
        if (value.length < 1)
            value += a
        else
            value += ", " + a
    }

    function onAccepted() {
        value = ""

        if (input_af.checked) add("af")
        if (input_ar.checked) add("ar")
        if (input_az.checked) add("az")
        if (input_be.checked) add("be")
        if (input_bg.checked) add("bg")
        if (input_br.checked) add("br")
        if (input_bs.checked) add("bs")
        if (input_ca.checked) add("ca")
        if (input_cs.checked) add("cs")
        if (input_cy.checked) add("cy")
        if (input_da.checked) add("da")
        if (input_de.checked) add("de")
        if (input_el.checked) add("el")
        if (input_en.checked) add("en")
        if (input_es.checked) add("es")
        if (input_et.checked) add("et")
        if (input_eu.checked) add("eu")
        if (input_fa.checked) add("fa")
        if (input_fi.checked) add("fi")
        if (input_fil.checked) add("fil")
        if (input_fr.checked) add("fr")
        if (input_ga.checked) add("ga")
        if (input_gd.checked) add("gd")
        if (input_gl.checked) add("gl")
        if (input_gsw.checked) add("gsw")
        if (input_he.checked) add("he")
        if (input_hi.checked) add("hi")
        if (input_hr.checked) add("hr")
        if (input_hu.checked) add("hu")
        if (input_id.checked) add("id")
        if (input_is.checked) add("is")
        if (input_it.checked) add("it")
        if (input_ja.checked) add("ja")
        if (input_ka.checked) add("ka")
        if (input_ko.checked) add("ko")
        if (input_lb.checked) add("lb")
        if (input_lt.checked) add("lt")
        if (input_lv.checked) add("lv")
        if (input_ms.checked) add("ms")
        if (input_mt.checked) add("mt")
        if (input_nb.checked) add("nb")
        if (input_nl.checked) add("nl")
        if (input_oc.checked) add("oc")
        if (input_pl.checked) add("pl")
        if (input_pt.checked) add("pt")
        if (input_ro.checked) add("ro")
        if (input_ru.checked) add("ru")
        if (input_si.checked) add("si")
        if (input_sk.checked) add("sk")
        if (input_sl.checked) add("sl")
        if (input_sr.checked) add("sr")
        if (input_sv.checked) add("sv")
        if (input_th.checked) add("th")
        if (input_tr.checked) add("tr")
        if (input_uk.checked) add("uk")
        if (input_ur.checked) add("ur")
        if (input_vi.checked) add("vi")
        if (input_zh.checked) add("zh")


        if (typeof callback == "function")
            callback(value);
    }

    Component.onCompleted:
    {
        var langs = value.split(',');
        for (var i=0; i < langs.length; ++i)
        {
            var l = langs[i].trim()

            if (l === "af") input_af.checked = true
            if (l === "ar") input_ar.checked = true
            if (l === "az") input_az.checked = true
            if (l === "be") input_be.checked = true
            if (l === "bg") input_bg.checked = true
            if (l === "br") input_br.checked = true
            if (l === "bs") input_bs.checked = true
            if (l === "ca") input_ca.checked = true
            if (l === "cs") input_cs.checked = true
            if (l === "cy") input_cy.checked = true
            if (l === "da") input_da.checked = true
            if (l === "de") input_de.checked = true
            if (l === "el") input_el.checked = true
            if (l === "en") input_en.checked = true
            if (l === "es") input_es.checked = true
            if (l === "et") input_et.checked = true
            if (l === "eu") input_eu.checked = true
            if (l === "fa") input_fa.checked = true
            if (l === "fi") input_fi.checked = true
            if (l === "fil") input_fil.checked = true
            if (l === "fr") input_fr.checked = true
            if (l === "ga") input_ga.checked = true
            if (l === "gd") input_gd.checked = true
            if (l === "gl") input_gl.checked = true
            if (l === "gsw") input_gsw.checked = true
            if (l === "he") input_he.checked = true
            if (l === "hi") input_hi.checked = true
            if (l === "hr") input_hr.checked = true
            if (l === "hu") input_hu.checked = true
            if (l === "id") input_id.checked = true
            if (l === "is") input_is.checked = true
            if (l === "it") input_it.checked = true
            if (l === "ja") input_ja.checked = true
            if (l === "ka") input_ka.checked = true
            if (l === "ko") input_ko.checked = true
            if (l === "lb") input_lb.checked = true
            if (l === "lt") input_lt.checked = true
            if (l === "lv") input_lv.checked = true
            if (l === "ms") input_ms.checked = true
            if (l === "mt") input_mt.checked = true
            if (l === "nb") input_nb.checked = true
            if (l === "nl") input_nl.checked = true
            if (l === "oc") input_oc.checked = true
            if (l === "pl") input_pl.checked = true
            if (l === "pt") input_pt.checked = true
            if (l === "ro") input_ro.checked = true
            if (l === "ru") input_ru.checked = true
            if (l === "si") input_si.checked = true
            if (l === "sk") input_sk.checked = true
            if (l === "sl") input_sl.checked = true
            if (l === "sr") input_sr.checked = true
            if (l === "sv") input_sv.checked = true
            if (l === "th") input_th.checked = true
            if (l === "tr") input_tr.checked = true
            if (l === "uk") input_uk.checked = true
            if (l === "ur") input_ur.checked = true
            if (l === "vi") input_vi.checked = true
            if (l === "zh") input_zh.checked = true

        }
    }
}
