#!/usr/bin/env python2.7

import os, collections

base_dir = "hierarchy"

planet = "planet/planet-latest.osm.pbf"
splitted_dir = "split"
helper_dir = "split/helper"

#####################################################

def ignore(d):
    return os.path.exists(d + "/ignore")

def get_from_parent(d, fname):
    dirs = d.split("/")
    base = base_dir.split("/")
    i = len(dirs)-1
    while i > len(base):
        k = ""
        for j in range(i): k = os.path.join(k, dirs[j])
        k = os.path.join(k, fname)
        if os.path.exists(k):
            return k
        i -= 1
    return None

def get_base_name(d):
    base_list = base_dir.split("/")
    rlist = d.split("/")
    ri = len(base_list)
    target = rlist[ri]
    ri+=1
    while ri < len(rlist):
        target += "-" + rlist[ri]
        ri += 1
    return target

def prepared(name):
    if name == planet: return ""
    return "$(HELP_DIR)/" + name + ".prepared"

def processed(name):
    if name == planet: return "$(HELP_DIR)/planet.processed"
    return "$(HELP_DIR)/" + name + ".processed"

def pbf(name):
    if name == planet: return name
    return "$(SPLIT_DIR)/" + name + ".pbf"

#####################################################
## MAIN

Depends = collections.defaultdict(list)

for root, folders, files in os.walk(base_dir):
    if "poly" in files:
        parent = get_from_parent(root, "poly")
        if parent is None:
            parent = planet
        else:
            parent = get_base_name(os.path.dirname(parent))

        target = get_base_name(root)

        poly = os.path.join(root, "poly")
        Depends[ parent ].append({ "target": target, "poly": poly })

fmake = open("Makefile.splitter", "w")

fmake.write("""
# This Makefile is generated by script prepare_splitter.py

SPLIT_DIR=%s
HELP_DIR=%s

""" % (splitted_dir, helper_dir))

fmake.write("""
all: $(SPLIT_DIR)/.directory $(HELP_DIR)/.directory $(HELP_DIR)/all_done
	echo All done

$(SPLIT_DIR)/.directory:
	mkdir -p $(SPLIT_DIR)
	touch $(SPLIT_DIR)/.directory

$(HELP_DIR)/.directory:
	mkdir -p $(HELP_DIR)
	touch $(HELP_DIR)/.directory

OSMOSIS=./osmosis
BUFFER=--buffer bufferCapacity=100000

""")

all_pbfs = []
for k in Depends:
    for j in Depends[k]:
        all_pbfs.append(j["target"])

        fmake.write(prepared(j["target"]) + ": $(HELP_DIR)/.directory " + processed(k) +
                    "\n\ttouch " + prepared(j["target"]) + "\n\n")

    fmake.write(processed(k) + ": $(HELP_DIR)/.directory " + prepared(k) + " ")
    for j in Depends[k]: fmake.write(" " + j["poly"])

    fmake.write("\n\t$(OSMOSIS) --read-pbf-fast " + pbf(k) + " --tee %d" % len(Depends[k]))
    for j in Depends[k]:
        fmake.write(" ${BUFFER} --bp file=%s ${BUFFER} --write-pbf %s" % (j["poly"], pbf(j["target"])))
    fmake.write("\n\ttouch " + processed(k) + "\n\n")

fmake.write("\n$(HELP_DIR)/all_done:")
for i in all_pbfs:
    fmake.write(" " + prepared(i))
fmake.write("\n\ttouch $(HELP_DIR)/all_done\n")

